######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 29 11:07:49 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hw1_2.cpp kbhit.cpp
