######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 10 13:00:02 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += miku.h MyWidget.h windows.h
SOURCES += main.cpp miku.cpp MyWidget.cpp windows.cpp
