######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 8 02:43:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyWidget.h
SOURCES += 1.cpp
